# -*- coding: utf-8 -*-
"""DL_Assignment4 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4SWX9kySERlDy2x--_ENP0fceqP5HKZ
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d meowmeowmeowmeowmeow/gtsrb-german-traffic-sign

!unzip gtsrb-german-traffic-sign.zip -d /content/gtsrb/

from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_path = "/content/gtsrb/Train"

gen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_ds = gen.flow_from_directory(
    data_path,
    target_size=(256, 256),
    batch_size=32,
    class_mode="categorical",
    subset='training'
)

test_ds = gen.flow_from_directory(
    data_path,
    target_size=(256, 256),
    batch_size=32,
    class_mode="categorical",
    subset='validation'
)

!pip install keras-tuner
import keras_tuner as kt
from tensorflow import keras
from keras import layers
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout

model = Sequential([
    layers.Conv2D(filters=32, kernel_size=(5,5), activation='relu', input_shape=(256,256,3)),
    layers.Conv2D(filters=32, kernel_size=(5,5), activation='relu'),
    layers.MaxPool2D(pool_size=(2, 2)),
    layers.Dropout(rate=0.25),

    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPool2D(pool_size=(2, 2)),
    layers.Dropout(rate=0.25),

    layers.Flatten(),
    layers.Dense(256, activation='relu'),
    layers.Dropout(rate=0.5),
    layers.Dense(43, activation='softmax')
 ]) # Output layer

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(train_ds, batch_size=32, epochs=15, validation_data=test_ds)

model.save("final_epoch_model.h5")

import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss')
plt.legend()
plt.show()

